# ======================================================================
#  Site Settings
# ======================================================================
title: "Prithviraj’s Blog"
tagline: "Exploring AI, Technology & Innovation"
description: "Personal blog by Prithviraj Bagchi — thoughts on AI, innovation, and technology."
url: "https://pb59.github.io"       # your GitHub Pages main URL
baseurl: "/ami1"                    # repo name for project site

author:
  name: "Prithviraj Bagchi"
  avatar: "/assets/img/avatar.png"   # optional (add image in /assets/img/)
  bio: "Delivery Architect | AI & GenAI Enthusiast"
  location: "Kolkata, India"
  email: "your-email@example.com"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/pb59"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/prithvirajbagchi"

# ======================================================================
#  Theme Settings
# ======================================================================
theme: jekyll-theme-chirpy
lang: en
timezone: Asia/Kolkata

twitter_username: pb59
github_username: pb59

markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

paginate: 10
paginate_path: "/page:num"

# ======================================================================
#  Navigation
# ======================================================================
navbar:
  - title: "Home"
    url: /
  - title: "Posts"
    url: /posts/
  - title: "About"
    url: /about/
  - title: "Contact"
    url: /contact/

# ======================================================================
#  Defaults
# ======================================================================
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
      comments: true
      toc: true

# ======================================================================
#  Exclusions
# ======================================================================
exclude:
  - node_modules
  - vendor
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - README.md
  - .github
  - .devcontainer
  - .vscode
  - tools

# ======================================================================
#  Feed and SEO
# ======================================================================
feed:
  path: feed.xml

seo:
  type: Blog
  name: "Prithviraj’s Blog"
  description: "Exploring AI, Technology, and Innovation."

# ======================================================================
#  Deployment
# ======================================================================
github:
  is_project_page: true
  repository_url: https://github.com/pb59/ami1
